-- Script de inserción de principios activos
-- Tabla: farmacia_dev.principios_activos
-- Generado: 2026-05-21
-- Total registros: 646

INSERT INTO farmacia_dev.principios_activos (nombre, descripcion, activo) VALUES
('Paracetamol', 'Analgésico y antipirético que inhibe la síntesis de prostaglandinas en el SNC', true),
('Ácido Acetilsalicílico', 'Analgésico, antipirético y antiinflamatorio inhibidor de COX-1 y COX-2, antiplaquetario', true),
('Metamizol', 'Analgésico y antipirético potente con efecto espasmolítico', true),
('Naproxeno', 'AINE inhibidor de COX-1 y COX-2, antiinflamatorio, analgésico y antipirético', true),
('Diclofenaco', 'AINE antiinflamatorio, analgésico y antipirético inhibidor de COX', true),
('Celecoxib', 'AINE inhibidor selectivo de COX-2 con menor riesgo gastrointestinal', true),
('Fentanilo', 'Opiáceo sintético potente de acción corta para analgesia severa', true),
('Bencilpenicilina', 'Antibiótico betalactámico de primera generación activo frente a gram positivos', true),
('Bencilpenicilina Benzatínica', 'Penicilina de depósito de acción prolongada usada en sífilis y profilaxis reumática', true),
('Cefalexina', 'Cefalosporina de 1ª generación oral para infecciones de piel y vías urinarias', true),
('Cefuroxima', 'Cefalosporina de 2ª generación activa frente a gram positivos y algunos gram negativos', true),
('Ciprofloxacino', 'Fluoroquinolona de 2ª generación de amplio espectro antibacteriano', true),
('Imipenem + Cilastatina', 'Antibiótico carbapenémico de amplio espectro combinado con inhibidor de dehidropeptidasa renal', true),
('Levofloxacino', 'Fluoroquinolona de 3ª generación activa frente a gram positivos y negativos', true),
('Norfloxacino', 'Fluoroquinolona de uso principalmente urinario', true),
('Penicilina V Potásica', 'Penicilina oral activa frente a gram positivos sensibles', true),
('Trimetoprim + Sulfametoxazol', 'Antibiótico combinado con acción sinérgica contra bacterias gram negativas y positivas', true),
('Amoxicilina + Ácido Clavulánico', 'Aminopenicilina con inhibidor de betalactamasas de amplio espectro', true),
('Anfotericina B', 'Antifúngico poliénico de amplio espectro para infecciones fúngicas graves sistémicas', true),
('Itraconazol', 'Antifúngico triazólico oral de amplio espectro', true),
('Ketoconazol', 'Antifúngico imidazólico de uso sistémico y tópico', true),
('Miconazol', 'Antifúngico imidazólico de uso principalmente tópico', true),
('Lamivudina + Zidovudina', 'Combinación antirretroviral de inhibidores nucleosídicos de la transcriptasa inversa (INTI)', true),
('Tenofovir + Emtricitabina', 'Combinación antirretroviral INTI de primera línea para VIH', true),
('Valaciclovir', 'Profármaco del aciclovir con mejor biodisponibilidad oral, antiviral contra herpes', true),
('Cloroquina', 'Antipalúdico y antiinflamatorio que inhibe la digestión del grupo hemo en el parásito', true),
('Praziquantel', 'Antihelmintico activo frente a trematodos y cestodos', true),
('Primaquina', 'Antipalúdico activo frente a formas hepáticas de Plasmodium vivax', true),
('Tinidazol', 'Antiprotozoario y antibacteriano anaerobio derivado del nitroimidazol', true),
('Estreptomicina', 'Aminoglucósido antibacteriano usado en tuberculosis y brucelosis', true),
('Isoniazida + Rifampicina + Pirazinamida', 'Combinación de fármacos de primera línea para tuberculosis en fase intensiva', true),
('Rifampicina + Isoniazida', 'Combinación antibacteriana de primera línea para tuberculosis', true),
('Amlodipino', 'Bloqueador de canales de calcio dihidropiridínico, antihipertensivo y antianginoso', true),
('Captopril', 'Inhibidor de la ECA de acción corta, antihipertensivo y cardioprotector', true),
('Diltiazem', 'Bloqueador de canales de calcio benzotiazepínico, antihipertensivo y antiarrítmico', true),
('Enalapril', 'Inhibidor de la ECA, antihipertensivo y cardioprotector', true),
('Hidralazina', 'Vasodilatador arterial directo, antihipertensivo especialmente en embarazo', true),
('Irbesartan', 'ARA II antihipertensivo bloqueador del receptor de angiotensina II', true),
('Losartan', 'ARA II antihipertensivo y nefroprotector bloqueador del receptor de angiotensina II', true),
('Metoprolol', 'Betabloqueador cardioselectivo antihipertensivo y antiarrítmico', true),
('Nitroglicerina', 'Nitrato orgánico vasodilatador coronario para angina de pecho', true),
('Ramipril', 'Inhibidor de la ECA antihipertensivo y cardioprotector con efecto nefroprotector', true),
('Enoxaparina', 'Heparina de bajo peso molecular anticoagulante subcutánea', true),
('Heparina', 'Anticoagulante parenteral que inhibe trombina y factor Xa', true),
('Simvastatina', 'Inhibidor de HMG-CoA reductasa hipolipemiante reductor de colesterol LDL', true),
('Beclometasona', 'Corticosteroide inhalado antiinflamatorio bronquial para asma', true),
('Ipratropio', 'Broncodilatador anticolinérgico inhalado para EPOC y asma', true),
('Bromuro de Hioscina', 'Antiespasmódico anticolinérgico para cólico abdominal y biliar', true),
('Esomeprazol', 'Inhibidor de la bomba de protones reductor de acidez gástrica', true),
('Pantoprazol', 'Inhibidor de la bomba de protones antiulceroso', true),
('Ranitidina', 'Antagonista H2 reductor de acidez gástrica (retirado en muchos países por contaminación con NDMA)', true),
('Hidróxido de Aluminio + Hidróxido de Magnesio', 'Antiácido de acción local combinado para síntomas de acidez y dispepsia', true),
('Sales de Rehidratación Oral', 'Solución electrolítica oral para rehidratación en diarrea y vómitos', true),
('Glimepirida', 'Sulfonilurea de 3ª generación hipoglucemiante oral para diabetes tipo 2', true),
('Insulina NPH', 'Insulina de acción intermedia para control glucémico en diabetes mellitus', true),
('Insulina Regular', 'Insulina de acción corta para control glucémico rápido preprandial', true),
('Sitagliptina', 'Inhibidor de DPP-4 antidiabético oral que potencia la secreción de insulina', true),
('Hidrocortisona', 'Corticosteroide de referencia con propiedades antiinflamatorias e inmunosupresoras', true),
('Levotiroxina', 'Hormona tiroidea sintética T4 para tratamiento del hipotiroidismo', true),
('Metilprednisolona', 'Corticosteroide de acción intermedia con potente efecto antiinflamatorio', true),
('Prednisolona', 'Corticosteroide oral antiinflamatorio e inmunosupresor forma activa de prednisona', true),
('Calcio + Vitamina D3', 'Suplemento combinado para prevención y tratamiento de osteoporosis y déficit de calcio', true),
('Cianocobalamina', 'Vitamina B12 esencial para eritropoyesis y función neurológica', true),
('Hierro Polimaltosado', 'Suplemento de hierro de alta biodisponibilidad y tolerabilidad para anemia ferropénica', true),
('Retinol', 'Vitamina A esencial para visión, inmunidad y crecimiento celular', true),
('Zinc Sulfato', 'Suplemento de zinc cofactor enzimático con propiedades inmunomoduladoras', true),
('Complejo B', 'Combinación de vitaminas del grupo B para soporte metabólico y función nerviosa', true),
('Sulfato Ferroso', 'Suplemento de hierro oral de primera línea para anemia ferropénica', true),
('Betametasona', 'Corticosteroide fluorado de alta potencia para uso antiinflamatorio tópico y sistémico', true),
('Tretinoína', 'Retinoide tópico para acné, hiperpigmentación y trastornos de queratinización', true),
('Óxido de Zinc', 'Protector dérmico, cicatrizante y astringente de uso tópico', true),
('Atropina', 'Anticolinérgico muscarínico para bradicardia, midriasis e intoxicación por organofosforados', true),
('Timolol', 'Betabloqueador no selectivo tópico oftálmico para reducción de presión intraocular', true),
('Medroxiprogesterona', 'Progestágeno sintético anticonceptivo y regulador menstrual', true),
('Clorfenamina', 'Antihistamínico de 1ª generación sedante para alergias y rinitis', true),
('Difenhidramina', 'Antihistamínico de 1ª generación con marcado efecto sedante y antiemético', true),
('Fexofenadina', 'Antihistamínico de 2ª generación no sedante para alergias estacionales', true),
('Loratadina', 'Antihistamínico de 2ª generación no sedante para alergias e urticaria', true),
('Escitalopram', 'Inhibidor selectivo de recaptación de serotonina (ISRS) antidepresivo de alta selectividad', true),
('Litio', 'Estabilizador del ánimo de primera línea para trastorno bipolar', true),
('Olanzapina', 'Antipsicótico atípico para esquizofrenia y episodios maníacos del trastorno bipolar', true),
('Sertralina', 'ISRS antidepresivo y ansiolítico de amplio uso clínico', true),
('Venlafaxina', 'IRSN antidepresivo inhibidor de recaptación de serotonina y norepinefrina', true),
('Clozapina', 'Antipsicótico atípico de segunda línea para esquizofrenia refractaria, requiere monitoreo hematológico', true),
('Ácido Valproico', 'Anticonvulsivante y estabilizador del ánimo de amplio espectro', true),
('Gabapentina', 'Antiepiléptico y analgésico neuropático análogo del GABA', true),
('Levetiracetam', 'Antiepiléptico de amplio espectro con mecanismo único de unión a proteína SV2A', true),
('Bupivacaína', 'Anestésico local amídico de acción prolongada para bloqueos nerviosos', true),
('Cetamina', 'Anestésico disociativo con propiedades analgésicas y broncodilatadoras', true),
('Succinilcolina', 'Relajante muscular despolarizante de acción ultracorta para intubación de secuencia rápida', true),
('Vecuronio', 'Relajante muscular no despolarizante de acción intermedia para cirugía', true),
('Doxorrubicina', 'Antibiótico antitumoral del grupo antraciclinas para múltiples tipos de cáncer', true),
('Glucosa', 'Carbohidrato simple fuente energética para fluidoterapia intravenosa', true),
('Cloruro de Sodio', 'Electrolito esencial para fluidoterapia, rehidratación y equilibrio osmótico', true),
('Ringer Lactato', 'Solución cristaloide isotónica para rehidratación y reposición de volumen', true),
('Levonorgestrel', 'Progestágeno sintético componente de anticonceptivos orales y anticonceptivo de emergencia', true),
('Pertuzumab', 'Anticuerpo monoclonal anti-HER2 antineoplásico para cáncer de mama HER2 positivo', true),
('Insulina recombinante humana NPH', 'Insulina humana de acción intermedia producida por tecnología de ADN recombinante', true),
('Prasterona enantato', 'Precursor de hormonas sexuales (DHEA) con acción androgénica débil', true),
('Sulfato ferroso', 'Suplemento de hierro oral para anemia ferropénica', true),
('Lenalidomida', 'Inmunomodulador antineoplásico análogo de talidomida para mieloma múltiple', true),
('Fluoxetina', 'ISRS pionero del grupo antidepresivo con larga vida media', true),
('Tamoxifeno', 'Modulador selectivo de receptores de estrógeno (SERM) antineoplásico para cáncer de mama', true),
('Metformina', 'Biguanida hipoglucemiante oral de primera línea en diabetes tipo 2 sin riesgo de hipoglucemia', true),
('Clonazepam', 'Benzodiazepina antiepiléptica y ansiolítica de acción prolongada', true),
('Lamivudina', 'INTI antirretroviral activo también frente a virus de hepatitis B', true),
('Colchicina', 'Antiinflamatorio específico para gota aguda y pericarditis recurrente', true),
('Irinotecan', 'Antineoplásico inhibidor de topoisomerasa I para cáncer colorrectal', true),
('Dextrán 70', 'Expansor plasmático coloidal de alto peso molecular para shock hipovolémico', true),
('Penicilamina', 'Quelante de metales pesados y DMARD para artritis reumatoide y enfermedad de Wilson', true),
('Abiraterona Acetato', 'Antineoplásico inhibidor de biosíntesis de andrógenos para cáncer de próstata resistente a castración', true),
('Carvedilol', 'Betabloqueador no selectivo con efecto alfa bloqueante para insuficiencia cardíaca e hipertensión', true),
('Capecitabine', 'Profármaco oral del 5-fluorouracilo antineoplásico para cáncer colorrectal y de mama', true),
('Warfarina', 'Anticoagulante oral antagonista de vitamina K para profilaxis y tratamiento tromboembólico', true),
('Suero Antiescorpiónico', 'Inmunoglobulina específica para neutralizar el veneno de escorpión', true),
('Ketamina (Cetamina)', 'Anestésico disociativo con propiedades analgésicas de amplio uso en emergencias y pediatría', true),
('Favipiravir', 'Antiviral de amplio espectro inhibidor de la ARN polimerasa viral ARN-dependiente', true),
('Cefixima', 'Cefalosporina oral de 3ª generación activa frente a gram negativos', true),
('Carbetocina', 'Análogo de oxitocina de acción prolongada para prevención de hemorragia postparto', true),
('Clorfenamina (Clorfeniramina)', 'Antihistamínico de 1ª generación sedante para alergias (nombre alternativo)', true),
('Metilprednisolona succinato sódico', 'Forma soluble de metilprednisolona para administración intravenosa o intramuscular', true),
('Timolol maleato', 'Betabloqueador tópico oftálmico en forma de sal maleato para glaucoma', true),
('Cilastatina', 'Inhibidor de la dehidropeptidasa renal que previene la degradación del imipenem', true),
('Ampicilina', 'Aminopenicilina semisintética de amplio espectro para infecciones diversas', true),
('Formaldehido', 'Desinfectante antiséptico de amplio espectro y fijador histológico', true),
('Metotrexato', 'Antimetabolito antagonista del folato antineoplásico e inmunosupresor para artritis reumatoide', true),
('Testosterona undecanoato', 'Éster de andrógeno de depósito para terapia de reemplazo hormonal masculino', true),
('Vacuna antineumococo (13 valente)', 'Vacuna conjugada que protege contra 13 serotipos de Streptococcus pneumoniae', true),
('Surfactante pulmonar', 'Agente tensioactivo para tratamiento del síndrome de dificultad respiratoria del recién nacido', true),
('Hipoclorito de sodio', 'Antiséptico y desinfectante oxidante de amplio espectro', true),
('Antitóxina tetánica', 'Inmunoglobulina antitetánica para tratamiento o profilaxis pasiva del tétanos', true),
('Ketoprofeno', 'AINE del grupo profeno antiinflamatorio y analgésico oral y tópico', true),
('Letrozol', 'Inhibidor de aromatasa de 3ª generación antineoplásico para cáncer de mama hormono-dependiente', true),
('Fitomenadiona (Vitamina K1)', 'Vitamina K natural esencial para síntesis de factores de coagulación', true),
('Cianocobalamina (B12)', 'Vitamina B12 (cobalamina) esencial para eritropoyesis y mantenimiento de la mielina neuronal', true),
('Ácido fólico', 'Vitamina B9 esencial para síntesis de ADN eritropoyesis y prevención de defectos del tubo neural', true),
('Bortezomib', 'Inhibidor del proteasoma antineoplásico de primera línea para mieloma múltiple', true),
('Azitromicina', 'Macrólido de amplio espectro con vida media prolongada y alta penetración tisular', true),
('Cotrimoxazol (Sulfametoxazol + Trimetoprim)', 'Antibiótico combinado sulfonamida-trimetoprim de amplio espectro', true),
('Dolutegravir', 'Antirretroviral inhibidor de la integrasa con alta barrera genética para VIH', true),
('Cloranfenicol', 'Antibiótico bacteriostático de amplio espectro reservado para infecciones graves', true),
('Glicerina', 'Humectante osmótico de uso tópico lubricante y laxante rectal', true),
('Amikacina', 'Aminoglucósido de amplio espectro activo frente a gram negativos multirresistentes', true),
('Nifedipino', 'Bloqueador de canales de calcio dihidropiridínico antihipertensivo y tocolítico', true),
('Oxígeno', 'Gas medicinal esencial para soporte ventilatorio y tratamiento de hipoxemia', true),
('Amitriptilina', 'Antidepresivo tricíclico con propiedades analgésicas para dolor neuropático crónico', true),
('Griseofulvina', 'Antifúngico oral para dermatofitosis de piel cabello y uñas', true),
('Carbón medicinal activado', 'Adsorbente gastrointestinal para intoxicaciones y sobredosis agudas', true),
('Misoprostol', 'Análogo de prostaglandina E1 para úlcera péptica inducción del parto y aborto farmacológico', true),
('Metronidazol', 'Antibiótico y antiprotozoario nitroimidazólico de amplio espectro activo en anaerobiosis', true),
('Duloxetina', 'IRSN antidepresivo y tratamiento del dolor neuropático y fibromialgia', true),
('Trastuzumab', 'Anticuerpo monoclonal anti-HER2 antineoplásico de primera línea para cáncer de mama', true),
('Pegaspargasa', 'Asparaginasa pegilada de mayor vida media antineoplásica para leucemia linfoblástica aguda', true),
('Lactulosa', 'Laxante osmótico disacárido sintético también usado en encefalopatía hepática', true),
('Dexametasona', 'Corticosteroide de alta potencia antiinflamatorio inmunosupresor y antiedema cerebral', true),
('Verapamilo', 'Bloqueador de canales de calcio fenilalquilamínico antiarrítmico y antihipertensivo', true),
('Gluconato Cálcico (Calcio Gluconato)', 'Suplemento de calcio parenteral para hipocalcemia e hiperpotasemia', true),
('Dasatinib', 'Inhibidor de tirosinquinasa BCR-ABL de segunda generación antineoplásico para LMC', true),
('Ácido nalidíxico', 'Quinolona de 1ª generación antibacteriano de uso urinario', true),
('Furosemida', 'Diurético de asa potente de acción rápida para edema e insuficiencia cardíaca', true),
('Multivitaminas', 'Combinación de vitaminas esenciales para cubrir requerimientos nutricionales diarios', true),
('Loperamida', 'Antidiarreico de acción local que reduce el peristaltismo intestinal sin efecto sistémico', true),
('Espiramicina', 'Macrólido antibacteriano especialmente indicado en toxoplasmosis durante el embarazo', true),
('Atenolol', 'Betabloqueador cardioselectivo antihipertensivo y antiarrítmico de acción prolongada', true),
('Alprazolam', 'Benzodiazepina ansiolítica y sedante para trastornos de ansiedad y pánico', true),
('Vacuna doble dT (difteria, Tétanos)', 'Vacuna de refuerzo combinada contra difteria y tétanos para adultos', true),
('Oligoelementos para nutricion parenteral', 'Mezcla de micronutrientes traza para nutrición parenteral total completa', true),
('Nimodipina', 'Bloqueador de canales de calcio con selectividad cerebrovascular para vasoespasmo post-hemorragia subaracnoidea', true),
('Meglumina antimoniato', 'Antiprotozoario pentavalente de primera línea para leishmaniasis visceral y cutánea', true),
('Isoniazida (INH)', 'Antibacteriano de primera línea bactericida para tuberculosis activa y profilaxis', true),
('Eter alifático dietilamino etanol', 'Compuesto de síntesis farmacéutica relacionado con anestésicos locales', true),
('Artemeter', 'Antimalárico derivado semisintético de la artemisinina para malaria por P. falciparum', true),
('Acetil Cisteina', 'Mucolítico y antídoto del paracetamol precursor del glutatión con propiedades antioxidantes', true),
('Terbinafina', 'Antifúngico de la clase alilaminas para dermatofitosis sistémica y tópica (onicomicosis)', true),
('Trimetoprima', 'Antibacteriano diaminopirimidínico inhibidor de la dihidrofolato reductasa bacteriana', true),
('Complemento nutricional (carmelo)', 'Suplemento nutricional específico con mezcla de macro y micronutrientes', true),
('Sevoflurano (Trifluorometil etil)', 'Anestésico inhalado halogenado para inducción y mantenimiento anestésico', true),
('Suxametonio (Succinil colina)', 'Relajante muscular despolarizante de acción ultrabreve para intubación rápida', true),
('Complemento nutricional (Nutribebé)', 'Fórmula nutricional adaptada específicamente para lactantes', true),
('Calcio (carbonato o citrato)', 'Suplemento mineral de calcio para prevención y tratamiento de osteoporosis', true),
('Tenofovir disoproxil fumarate', 'Profármaco INTI antirretroviral de primera línea para VIH y hepatitis B crónica', true),
('Isosorbida Mononitrato', 'Nitrato orgánico vasodilatador de larga duración para profilaxis de angina de pecho', true),
('Eritropoyetina', 'Hormona glucoproteica estimulante de eritropoyesis para anemia en insuficiencia renal crónica', true),
('Fluoruro de sodio', 'Mineral preventivo de caries dental con efecto remineralizante del esmalte', true),
('Interferon beta', 'Inmunomodulador para reducción de brotes en esclerosis múltiple recurrente-remitente', true),
('Metilfenidato', 'Estimulante del SNC inhibidor de recaptación de dopamina y norepinefrina para TDAH', true),
('Bencilpenicilina benzatínica', 'Penicilina de depósito de acción muy prolongada para sífilis y profilaxis reumática', true),
('Zinc (Zn)', 'Zinc elemental micronutriente esencial cofactor de más de 300 enzimas', true),
('Anastrozol', 'Inhibidor de aromatasa de 3ª generación antineoplásico para cáncer de mama posmenopáusico', true),
('Vancomicina', 'Glucopéptido antibacteriano de reserva para gram positivos resistentes incluyendo MRSA y SARM', true),
('Dacarbazina', 'Agente alquilante antineoplásico para melanoma metastásico y linfoma de Hodgkin', true),
('Ofloxacina', 'Fluoroquinolona de 2ª generación antibacteriana de amplio espectro sistémico y tópico', true),
('Dimenhidrinato', 'Antihistamínico con propiedades antieméticas y antivertiginosas para cinetosis', true),
('Triptorelina', 'Análogo de GnRH de acción prolongada para cáncer de próstata endometriosis y pubertad precoz', true),
('Complejo B (B1, B6)', 'Vitaminas del grupo B incluyendo tiamina y piridoxina para metabolismo energético y nervioso', true),
('Dicloxacilina sódica', 'Penicilina resistente a penicilinasas activa frente a Staphylococcus aureus sensible a meticilina', true),
('Mebendazol', 'Antihelmintico de amplio espectro activo frente a nematodos intestinales como áscaris y oxiuros', true),
('Naratriptan', 'Triptán agonista selectivo 5-HT1B/1D para tratamiento agudo de migraña con efecto prolongado', true),
('Acetazolamida', 'Inhibidor de anhidrasa carbónica diurético antiepiléptico y para mal de altura', true),
('Vaselina sólida', 'Emoliente petrolátum excipiente y protector cutáneo de uso tópico', true),
('Ibuprofeno', 'AINE del grupo profeno analgésico antipirético y antiinflamatorio de amplio uso', true),
('Dorzolamida', 'Inhibidor tópico oftálmico de anhidrasa carbónica para reducción de presión intraocular', true),
('Etamsilato', 'Hemostático que estabiliza la pared capilar y reduce el tiempo de sangrado', true),
('Ácido salicílico', 'Queratolítico y antiséptico tópico para hiperqueratosis y acné', true),
('Eritromicina', 'Antibiótico macrólido de amplio espectro alternativa a la penicilina en alérgicos', true),
('Propofol', 'Anestésico intravenoso de acción ultracorta para inducción y mantenimiento anestésico en UCI', true),
('Ketorolaco', 'AINE parenteral y oral con potente efecto analgésico equivalente a opioides leves', true),
('Ácido acético (Ácido tricloroacético)', 'Agente cáustico queratolítico para verrugas y lesiones cervicales precancerosas', true),
('Teofilina', 'Broncodilatador xantínico inhibidor de fosfodiesterasa para asma y EPOC grave', true),
('Diazepam', 'Benzodiazepina ansiolítica anticonvulsivante relajante muscular y sedante', true),
('Telmisartán', 'ARA II de larga vida media antihipertensivo con efecto metabólico adicional', true),
('Cafeína Citrato', 'Estimulante del SNC metilxantina para tratamiento de apnea del prematuro', true),
('Heparina de bajo peso molecular', 'Anticoagulante con mejor biodisponibilidad subcutánea y menor riesgo de trombocitopenia', true),
('Gemcitabina', 'Antimetabolito análogo de citidina antineoplásico para cáncer de páncreas y pulmón', true),
('Glibenclamida', 'Sulfonilurea de 2ª generación hipoglucemiante oral que estimula secreción de insulina', true),
('Alimentos Terapéutico Listo para Uso (ATLU)', 'Alimento terapéutico de alta densidad energética para desnutrición aguda severa', true),
('Fluconazol', 'Antifúngico triazólico oral y parenteral para candidiasis sistémica y criptococosis meníngea', true),
('Bencilpenicilina procaínica', 'Penicilina de depósito de absorción lenta para infecciones bacterianas moderadas', true),
('Solución Básica', 'Solución de electrolitos de pH alcalino para uso en diálisis y preparaciones farmacéuticas', true),
('Etambutol', 'Antibacteriano de primera línea para tuberculosis que inhibe síntesis de pared celular micobacteriana', true),
('Vinblastina', 'Alcaloide de la vinca antineoplásico que inhibe la polimerización de tubulina', true),
('Atazanavir (sulfato)', 'Antirretroviral inhibidor de la proteasa del VIH en forma de sal sulfato', true),
('Atazanavir', 'Antirretroviral inhibidor de la proteasa del VIH con dosificación una vez al día', true),
('Vacuna BCG', 'Vacuna viva atenuada contra tuberculosis que previene formas graves en niños', true),
('Fibra natural', 'Suplemento de fibra dietética soluble e insoluble para regulación intestinal', true),
('Labetalol', 'Betabloqueador no selectivo con efecto alfa-1 bloqueante antihipertensivo oral y parenteral', true),
('Albendazol', 'Antihelmintico de amplio espectro activo frente a nematodos cestodos y quistes hidatídicos', true),
('Clofazimina', 'Antibacteriano antiinflamatorio derivado de riminofenazina para lepra y micobacterias no tuberculosas', true),
('Mifepristona', 'Antiprogestágeno y antiglucocorticosteroide para aborto farmacológico y anticoncepción de emergencia', true),
('Levotiroxina sódica', 'Hormona tiroidea sintética T4 de reemplazo para hipotiroidismo primario y central', true),
('Clobetasol', 'Corticosteroide tópico de muy alta potencia para dermatosis inflamatorias graves y refractarias', true),
('Amiodarona (clorhidrato)', 'Antiarrítmico de clase III de amplio espectro para arritmias ventriculares y supraventriculares', true),
('Erlotinib', 'Inhibidor selectivo del receptor EGFR tirosinquinasa antineoplásico para cáncer de pulmón no microcítico', true),
('Cloranfenicol succinato sódico', 'Forma soluble de cloranfenicol para administración parenteral en infecciones graves', true),
('Iodo povidona (Yodopovidona)', 'Antiséptico de amplio espectro con yodo activo para heridas y preparación quirúrgica', true),
('Dactinomicina', 'Antibiótico antitumoral actinomicina antineoplásico para tumores de Wilms y sarcomas', true),
('Nitrofural (Nitrofurazona)', 'Antibacteriano tópico nitrofuránico para quemaduras y heridas infectadas', true),
('Etinilestradiol', 'Estrógeno sintético componente estrogénico de anticonceptivos orales combinados', true),
('Rifampicina, Clofazimina, Dapsona', 'Poliquimioterapia estándar de la OMS para lepra multibacilar', true),
('Rivaroxabán', 'Anticoagulante oral inhibidor directo del factor Xa para tromboembolismo venoso y fibrilación auricular', true),
('Sucralfato', 'Citoprotector gástrico que forma barrera protectora sobre mucosa ulcerada', true),
('Solución ringer lactato', 'Solución cristaloide isotónica con lactato para rehidratación y reposición de volumen', true),
('Calcio', 'Mineral esencial para función ósea muscular cardíaca y coagulación sanguínea', true),
('Carbidopa', 'Inhibidor de DOPA descarboxilasa periférica usado en combinación con levodopa para Parkinson', true),
('Docetaxel', 'Taxano antineoplásico que estabiliza microtúbulos para cáncer de mama pulmón y próstata', true),
('Pregabalina', 'Antiepiléptico y analgésico neuropático análogo del GABA para fibromialgia y dolor neuropático', true),
('Solucion Acida', 'Solución de pH ácido para usos médicos específicos como preparación de dializados', true),
('Ipratropio bromuro', 'Bromuro de ipratropio broncodilatador anticolinérgico inhalado para EPOC y asma', true),
('Complemento nutricional', 'Suplemento de macronutrientes y micronutrientes esenciales para necesidades específicas', true),
('Azatioprina', 'Inmunosupresor antimetabolito tiopurídico para trasplantes y enfermedades autoinmunes', true),
('Terlipresina', 'Análogo de vasopresina vasoconstrictor esplácnico para hemorragia variceal y síndrome hepatorrenal', true),
('Contraste iodado', 'Medio de contraste yodado iónico o no iónico para estudios de imagen radiológica', true),
('Bisoprolol', 'Betabloqueador cardioselectivo de alta selectividad para insuficiencia cardíaca estable e hipertensión', true),
('Medroxiprogesterona acetato', 'Progestágeno sintético inyectable de depósito como anticonceptivo trimestral', true),
('Gentamicina sulfato', 'Aminoglucósido antibacteriano de amplio espectro para infecciones graves por gram negativos', true),
('Proximetacaina (Proparacaina)', 'Anestésico local tópico de acción rápida para uso oftalmológico diagnóstico', true),
('Noretisterona acetato', 'Progestágeno sintético de 19-nortestosterona componente anticonceptivo y hemostático', true),
('Diclofenaco Sódico', 'AINE en forma de sal sódica antiinflamatorio analgésico y antipirético', true),
('Glicerol (Glicerina)', 'Humectante y laxante osmótico rectal de uso tópico y oral', true),
('Enzalutamida', 'Antiandrógeno de nueva generación inhibidor del receptor de andrógenos para cáncer de próstata', true),
('Estradiol valerianato', 'Éster del estradiol de liberación prolongada para terapia hormonal femenina sustitutiva', true),
('Suero Antiofídico Botrópico Crotàlico', 'Inmunoglobulina específica bivalente contra venenos de víboras Bothrops y Crotalus', true),
('Nitroglicerina (Trinitrato de glicerol)', 'Nitrato orgánico vasodilatador coronario para angina aguda y crónica', true),
('Solución ringer normal', 'Solución cristaloide isotónica con electrolitos para reposición de volumen', true),
('Sulfadiazina de plata', 'Antibacteriano tópico de amplio espectro para quemaduras e infecciones cutáneas graves', true),
('Hidroxicloroquina sulfato', 'Antipalúdico y antirreumático con efecto inmunomodulador en lupus y artritis reumatoide', true),
('Cloroquina fosfato', 'Sal fosfato de cloroquina antipalúdico y antiinflamatorio en enfermedades del tejido conectivo', true),
('Bupivacaina clorhidrato con Epinefrina sin conservante', 'Anestésico local de acción prolongada con vasoconstrictor para mayor duración', true),
('Bicalutamida', 'Antiandrógeno no esteroideo para cáncer de próstata avanzado', true),
('Sofosbuvir', 'Antiviral pangenotípico de acción directa inhibidor de la ARN polimerasa NS5B del VHC', true),
('Budesonida', 'Corticosteroide inhalado de alta potencia para asma EPOC y enfermedad inflamatoria intestinal', true),
('Insulina zinc cristalina recombinante humana', 'Insulina recombinante en formulación zinc cristalina de acción ultrarrápida', true),
('Valganciclovir', 'Profármaco oral del ganciclovir antiviral para retinitis y otras infecciones por citomegalovirus', true),
('Estreptomicina sulfato', 'Aminoglucósido sal sulfato para tuberculosis pulmonar y brucelosis', true),
('Fenobarbital', 'Barbitúrico antiepiléptico de primera línea en países en desarrollo y sedante', true),
('Estradiol', 'Estrógeno natural endógeno para terapia hormonal femenina sustitutiva', true),
('Ácido Fólico (Chispitas nutricionales)', 'Ácido fólico en formato de micronutrientes en polvo para prevención de desnutrición en niños', true),
('Ledipasvir', 'Antiviral de acción directa inhibidor NS5A del virus de la hepatitis C para genotipo 1', true),
('Hierro (como bisglicina quelato)', 'Forma quelada orgánica de hierro con alta biodisponibilidad y mínimos efectos adversos', true),
('Micofenolato de mofetilo', 'Inmunosupresor antimetabolito inhibidor de síntesis de purinas para prevención de rechazo', true),
('Iodo (Yodo)', 'Micronutriente esencial para síntesis de hormonas tiroideas T3 y T4', true),
('Doxorrubicina liposomal pegilada', 'Antraciclina encapsulada en liposomas PEGilados para mayor tolerabilidad y menor cardiotoxicidad', true),
('Nifurtimox', 'Antiprotozoario nitrofuránico para enfermedad de Chagas aguda y tripanosomiasis africana', true),
('Estradiol valerato', 'Éster de estradiol de liberación prolongada para terapia hormonal femenina', true),
('Agua para inyección', 'Agua estéril apirógena libre de endotoxinas para reconstitución de medicamentos parenterales', true),
('Toxoide tetánico adsorbido', 'Vacuna antitetánica que induce inmunidad activa contra la toxina tetánica', true),
('Finasterida', 'Inhibidor de la 5-alfa reductasa para hiperplasia prostática benigna y alopecia androgénica masculina', true),
('Vacuna antipoliomielítica inactivada', 'Vacuna inactivada tipo Salk con tres serotipos para inmunización contra poliomielitis', true),
('Norgestrel', 'Progestágeno sintético componente de anticonceptivos orales combinados', true),
('Hierro', 'Mineral esencial para síntesis de hemoglobina mioglobina y citocromos', true),
('Dobutamina clorhidrato', 'Inotrópico positivo selectivo beta-1 para insuficiencia cardíaca aguda y cardiogénica', true),
('Ácido dimercaptosuccinico', 'Quelante oral de metales pesados especialmente plomo y mercurio para intoxicaciones', true),
('Metadona', 'Opioide sintético de acción prolongada para dolor severo crónico y terapia de sustitución en dependientes de opioides', true),
('Enzimas pancreáticas (Lipasa, Proteasa y Amilasa)', 'Sustitución enzimática exógena en insuficiencia pancreática exocrina y fibrosis quística', true),
('Bupivacaina clorhidrato', 'Anestésico local amídico de larga duración para infiltración y bloqueos nerviosos regionales', true),
('Fingolimod', 'Inmunomodulador modulador del receptor S1P para esclerosis múltiple recurrente-remitente', true),
('Sulfato de Bario', 'Medio de contraste radiopaco inerte para estudios gastrointestinales con rayos X', true),
('Leucovorina (Folinato de calcio)', 'Folato activo para rescate de toxicidad del metotrexato y potenciación del fluorouracilo', true),
('Peróxido de hidrógeno (Agua oxigenada)', 'Antiséptico oxidante de uso tópico para limpieza de heridas superficiales', true),
('Darunavir', 'Antirretroviral inhibidor de proteasa del VIH de segunda generación con alta barrera genética', true),
('Paclitaxel', 'Taxano antineoplásico que estabiliza microtúbulos para cáncer de ovario mama y pulmón', true),
('Hidrocortisona acetato', 'Éster acetato de hidrocortisona corticosteroide tópico de baja-media potencia', true),
('Resina de Podofilo (Podofilina)', 'Citotóxico tópico que inhibe la mitosis para verrugas genitales y condilomas acuminados', true),
('Daunorrubicina', 'Antraciclina antineoplásica para leucemia mieloide y linfoblástica aguda', true),
('Micronutrientes (Vit. C, Fe, Zn)', 'Vitamina C hierro y zinc micronutrientes para apoyo nutricional e inmunológico', true),
('Levotiroxina sòdica', 'Hormona tiroidea T4 sintética para tratamiento del hipotiroidismo (ortografía alternativa)', true),
('Eritromicina (estearato)', 'Sal estearato de eritromicina para formulaciones orales con mejor sabor y tolerabilidad', true),
('Vacuna antiamarílica', 'Vacuna de virus vivo atenuado cepa 17D contra la fiebre amarilla con protección duradera', true),
('Vacuna SRP (Sarampión, Rubeola, Paperas)', 'Vacuna triple viral combinada contra sarampión rubeola y parotiditis', true),
('Litio carbonato', 'Sal carbonato de litio estabilizador del ánimo para manía y depresión bipolar', true),
('Suero Antiofídico Botrópico Laquésico', 'Inmunoglobulina bivalente contra veneno de serpientes Bothrops y Lachesis muta', true),
('Vacuna Antirotavírica', 'Vacuna oral de virus vivo atenuado para prevención de gastroenteritis por rotavirus en lactantes', true),
('Solución Fisiológica', 'Solución isotónica de cloruro de sodio al 0,9% para uso intravenoso y lavados', true),
('Etopósido', 'Inhibidor de topoisomerasa II antineoplásico para cáncer de pulmón testicular y linfomas', true),
('Clorhexidina gluconato', 'Antiséptico de amplio espectro con efecto residual para piel mucosas y heridas quirúrgicas', true),
('Ceftriaxona', 'Cefalosporina de 3ª generación parenteral de amplio espectro y larga vida media', true),
('Ácido Ursodeoxicólico', 'Ácido biliar para disolución de cálculos biliares y tratamiento de colestasis hepática', true),
('Solución de preservación de órganos sòlidos HTK', 'Solución cardiopléjica HTK para preservación hipotérmica de órganos sólidos en trasplante', true),
('Quinina (diclorhidrato)', 'Sal diclorhidrato de quinina antipalúdico clásico para malaria grave por P. falciparum', true),
('Noretisterona', 'Progestágeno sintético de 19-nortestosterona para anticoncepción y regulación menstrual', true),
('Prednisona', 'Corticosteroide oral profármaco de la prednisolona para enfermedades inflamatorias y autoinmunes', true),
('Emulsión de lípidos', 'Fuente de ácidos grasos esenciales y calorías para nutrición parenteral total', true),
('Propinoxato', 'Antiespasmódico anticolinérgico para espasmos del tracto gastrointestinal y urinario', true),
('Fenitoína', 'Antiepiléptico estabilizador de membrana que inhibe canales de sodio voltaje-dependientes', true),
('Leucovorina', 'Folato activo (ácido folínico) para rescate de metotrexato y potenciación de quimioterapia', true),
('Formula Infantil', 'Fórmula láctea adaptada para lactantes cuando no es posible la lactancia materna', true),
('Paracetamol (Acetaminofeno)', 'Analgésico y antipirético ampliamente utilizado también conocido como acetaminofeno', true),
('Atracurio besilato', 'Relajante muscular no despolarizante de acción intermedia con metabolismo independiente del hígado', true),
('Fludarabina', 'Análogo nucleosídico purínico antineoplásico para leucemia linfocítica crónica y linfomas', true),
('Amoxicilina', 'Aminopenicilina semisintética oral de amplio espectro para infecciones respiratorias y urinarias', true),
('Piridoxina (B6)', 'Vitamina B6 cofactor en metabolismo de aminoácidos y síntesis de neurotransmisores', true),
('Estrógenos conjugados', 'Mezcla de estrógenos de origen equino para terapia hormonal en menopausia', true),
('Flunarizina', 'Bloqueador de canales de calcio antimigrañoso y antivertiginoso para vértigo crónico', true),
('Hidralazina clorhidrato', 'Vasodilatador arterial directo antihipertensivo para crisis y preeclampsia', true),
('Gadobutrol', 'Medio de contraste macrocíclico de gadolinio de alta concentración para resonancia magnética', true),
('Complemento nutricional (Diabético)', 'Fórmula nutricional especializada de bajo índice glucémico para pacientes diabéticos', true),
('Haloperidol', 'Antipsicótico típico del grupo butirofenona para psicosis aguda y crónica', true),
('Fentanilo sin conservante', 'Opiáceo sintético en formulación libre de conservantes para uso intratecal o epidural', true),
('Ciclofosfamida', 'Agente alquilante antineoplásico e inmunosupresor para linfomas leucemias y artritis reumatoide grave', true),
('Tenecteplasa', 'Trombolítico fibrinolítico recombinante de administración en bolo para infarto agudo de miocardio', true),
('Solución de glucosa', 'Solución de dextrosa al 5% o 10% para fluidoterapia y aporte calórico intravenoso', true),
('Risperidona', 'Antipsicótico atípico antagonista D2/5-HT2A para esquizofrenia y trastorno bipolar', true),
('Midazolam', 'Benzodiazepina de acción corta para sedación procedimiento anestesia y convulsiones', true),
('Mesna (Mercapto etilsulfonato sódico)', 'Uroprotector que inactiva la acroleína en orina previniendo cistitis hemorrágica por ciclofosfamida', true),
('Eritromicina (etilsuccinato)', 'Éster etilsuccinato de eritromicina con mejor absorción oral y menor irritación gástrica', true),
('Solución glucosada clorurada', 'Solución combinada de glucosa y cloruro de sodio para fluidoterapia de mantenimiento', true),
('Nimotuzumab', 'Anticuerpo monoclonal anti-EGFR con propiedades antiangiogénicas para glioblastoma y carcinomas', true),
('Ondansetrón', 'Antiemético antagonista selectivo del receptor 5-HT3 altamente efectivo en quimioterapia y cirugía', true),
('Rituximab', 'Anticuerpo monoclonal anti-CD20 para linfomas B no Hodgkin y enfermedades autoinmunes como AR', true),
('Kanamicina', 'Aminoglucósido antibacteriano de segunda línea para tuberculosis multirresistente', true),
('Artesunato', 'Antimalárico semisintético derivado de artemisinina de elección para malaria grave por P. falciparum', true),
('Desmopresina acetato', 'Análogo sintético de vasopresina antidiurético y hemostático para diabetes insípida y hemofilia A leve', true),
('Mivacuronio', 'Relajante muscular no despolarizante de acción muy corta para procedimientos quirúrgicos breves', true),
('Corticoide', 'Corticosteroide genérico con propiedades antiinflamatorias inmunosupresoras y antialérgicas', true),
('Ergometrina maleato', 'Alcaloide ergotamínico uterotónico para tratamiento y prevención de hemorragia postparto', true),
('Complemento nutricional (Nutri Mama con Cañahua)', 'Suplemento especializado con nutrientes clave para mujeres embarazadas y lactantes', true),
('Acido p-aminosalicilico', 'Antibacteriano bacteriostático de segunda línea para tuberculosis multirresistente y extensamente resistente', true),
('Betametasona (fosfato)', 'Corticosteroide inyectable de alta potencia para maduración pulmonar fetal en amenaza de parto prematuro', true),
('Cabergolina', 'Agonista dopaminérgico D2 de larga acción para hiperprolactinemia y enfermedad de Parkinson', true),
('Leflunomida', 'DMARD inmunomodulador inhibidor de síntesis de pirimidinas para artritis reumatoide activa', true),
('Rocuronio bromuro', 'Relajante muscular no despolarizante de inicio de acción rápido para intubación y cirugía', true),
('Heparina sódica', 'Anticoagulante parenteral de acción rápida sal sódica para trombosis venosa profunda y embolia pulmonar', true),
('Espironolactona', 'Diurético ahorrador de potasio antagonista de aldosterona para insuficiencia cardíaca e hiperaldosteronismo', true),
('Digoxina', 'Glucósido cardíaco inotrópico positivo para insuficiencia cardíaca y control de frecuencia en FA', true),
('Cloruro de sodio', 'Electrolito fundamental para equilibrio hidroelectrolítico osmolaridad y fluidoterapia', true),
('Antigripal (Paracetamol + Cafeína)', 'Combinación de paracetamol con otros activos para alivio sintomático de gripe y resfriado', true),
('Vacuna SR (Sarampión, Rubeola)', 'Vacuna bivalente de virus vivos atenuados contra sarampión y rubeola', true),
('Bromocriptina', 'Agonista dopaminérgico D2 para hiperprolactinemia galactorrea y enfermedad de Parkinson', true),
('Cefotaxima', 'Cefalosporina de 3ª generación parenteral activa frente a gram negativos y meningitis bacteriana', true),
('Aceite vitaminado (alimento)', 'Suplemento oleoso con vitaminas liposolubles para apoyo nutricional', true),
('Lidocaína', 'Anestésico local amídico y antiarrítmico de clase IB de amplio uso clínico', true),
('Cefazolina', 'Cefalosporina de 1ª generación parenteral de primera elección para profilaxis quirúrgica', true),
('Losartán', 'ARA II antihipertensivo y nefroprotector con efecto hiperuricosúrico', true),
('Levofloxacina', 'Fluoroquinolona de 3ª generación para infecciones respiratorias comunitarias y urinarias', true),
('Bedaquilina', 'Diariltiquinolina inhibidor de ATP sintasa micobacteriana para tuberculosis multirresistente', true),
('Factor VIII de la coagulación', 'Concentrado de factor VIII para tratamiento de hemofilia A congénita o adquirida', true),
('Vacuna hepatitis B', 'Vacuna recombinante de antígeno de superficie para inmunización activa contra hepatitis B', true),
('Simeticona', 'Antiespumante de acción local que reduce la tensión superficial de gases intestinales', true),
('Ácido acetil salicílico', 'Analgésico antipirético antiinflamatorio e inhibidor plaquetario irreversible de COX-1', true),
('Fenofibrato', 'Fibrato activador de PPAR-alfa para hipertrigliceridemia y dislipemia mixta', true),
('Vincristina', 'Alcaloide de la vinca antineoplásico que inhibe la polimerización de tubulina para leucemia y linfoma', true),
('Metotrexate', 'Antimetabolito antagonista del folato antineoplásico e inmunosupresor (nombre alternativo de metotrexato)', true),
('Cafeína', 'Metilxantina estimulante del SNC con efecto broncodilatador y analgésico coadyuvante', true),
('Cefepima', 'Cefalosporina de 4ª generación parenteral de amplio espectro activa frente a Pseudomonas aeruginosa', true),
('Amlodipina', 'Bloqueador de canales de calcio dihidropiridínico antihipertensivo de acción prolongada', true),
('Ungüento dérmico eucalipto mentol', 'Emoliente tópico descongestionante con propiedades analgésicas y antisépticas leves', true),
('Imipenem', 'Carbapenémico betalactámico de amplio espectro para infecciones graves por gérmenes multirresistentes', true),
('Ivermectina', 'Antiparasitario de amplio espectro activo frente a nematodos y ectoparásitos como sarna y pediculosis', true),
('Anestésico (genérico)', 'Agente farmacológico que produce pérdida reversible de la sensibilidad local o general', true),
('Vasoconstrictor con o sin Cafeína', 'Combinación para uso dental o tópico que prolonga el efecto anestésico local', true),
('Ciproterona acetato', 'Antiandrogénico esteroideo para hirsutismo acné severo y cáncer de próstata', true),
('Busulfano', 'Agente alquilante antineoplásico para leucemia mieloide crónica y acondicionamiento en trasplante de médula', true),
('Inhibidor betalactamasa', 'Compuesto que inhibe enzimas betalactamasas bacterianas potenciando antibióticos betalactámicos', true),
('Tenofovir', 'Análogo nucleotídico antirretroviral para VIH y hepatitis B en combinaciones', true),
('Pirazinamida', 'Antibacteriano bactericida de primera línea para tuberculosis activo en ambiente ácido', true),
('Enalapril maleato', 'Sal maleato del enalapril inhibidor de la ECA antihipertensivo y cardioprotector', true),
('Tropicamida', 'Midriático y ciclopléjico anticolinérgico de acción corta para examen oftalmológico', true),
('Oseltamivir', 'Antiviral inhibidor de neuraminidasa para tratamiento y profilaxis de influenza A y B', true),
('Ketotifeno', 'Antihistamínico y estabilizador de mastocitos oral y tópico oftálmico antialérgico', true),
('Tacrolimus', 'Inmunosupresor macrólido inhibidor de calcineurina para prevención de rechazo en trasplantes', true),
('Bacitracina', 'Antibiótico polipeptídico tópico activo frente a gram positivos para infecciones cutáneas', true),
('Propranolol', 'Betabloqueador no selectivo para hipertensión arritmias temblor y profilaxis de migraña', true),
('Alcohol etílico (Etanol)', 'Antiséptico y desinfectante cutáneo de amplio espectro al 70%', true),
('Omeprazol', 'Inhibidor de la bomba de protones de primera línea para úlcera péptica y ERGE', true),
('Etionamida', 'Antibacteriano de segunda línea que inhibe la síntesis de ácidos micólicos en tuberculosis multirresistente', true),
('Bicarbonato de sodio p/hemodiálisis', 'Tampón bicarbonato alcalino concentrado para preparación de líquido de hemodiálisis', true),
('Triclabendazol', 'Antihelmintico bencimidazólico específico para fasciolasis hepática por Fasciola hepatica', true),
('Latanoprost', 'Análogo de prostaglandina F2-alfa para reducción de presión intraocular en glaucoma de ángulo abierto', true),
('Rosuvastatina', 'Estatina de alta potencia inhibidora de HMG-CoA reductasa para reducción de colesterol LDL', true),
('Tazobactam', 'Inhibidor de betalactamasas que potencia la actividad de la piperacilina frente a gram negativos', true),
('Flutamida', 'Antiandrógeno no esteroideo para cáncer de próstata metastásico en combinación con agonistas GnRH', true),
('Meglumina diatrizoato', 'Medio de contraste yodado iónico de alta osmolaridad para estudios radiológicos', true),
('Edetato sódico de calcio (EDTA)', 'Quelante de metales pesados especialmente plomo para intoxicaciones agudas y crónicas', true),
('Epinefrina', 'Catecolamina endógena vasopresora broncodilatadora y cardioestimulante para emergencias', true),
('Carbonato de sodio', 'Agente alcalinizante utilizado en formulaciones farmacéuticas y como excipiente', true),
('Dinitrato de isosorbida (Isosorbide dinitrato)', 'Nitrato orgánico vasodilatador para angina de pecho crónica e insuficiencia cardíaca', true),
('Adenosina', 'Nucleósido antiarrítmico para conversión de taquicardia supraventricular paroxística a ritmo sinusal', true),
('Linezolid', 'Oxazolidinona antibacteriana de último recurso para gram positivos multirresistentes MRSA y VRE', true),
('Neomicina sulfato', 'Aminoglucósido tópico antibacteriano para infecciones cutáneas y preparación intestinal preoperatoria', true),
('Interferon alfa 2b recombinante', 'Inmunomodulador antiviral y antitumoral para hepatitis C B y leucemia de células pilosas', true),
('Dimercaprol (B.A.L.)', 'Quelante de metales pesados arsénico mercurio y oro para intoxicaciones agudas', true),
('Albúmina humana', 'Proteína plasmática coloidal para reposición de volumen y tratamiento de hipoalbuminemia grave', true),
('Mefloquina', 'Antipalúdico para profilaxis y tratamiento de malaria resistente a cloroquina', true),
('Vacuna Haemophilus influenzae B', 'Vacuna conjugada contra Haemophilus influenzae tipo b para prevención de meningitis en niños', true),
('Meloxicam', 'AINE preferente inhibidor de COX-2 con menor riesgo gastrointestinal que AINEs clásicos', true),
('Metamizol (Dipirona)', 'Analgésico antipirético potente con efecto espasmolítico para dolor severo y fiebre refractaria', true),
('Tocoferol (Vitamina E)', 'Vitamina liposoluble antioxidante que protege membranas celulares de la peroxidación lipídica', true),
('Zidovudina', 'INTI antirretroviral pionero para VIH también usado en profilaxis de transmisión vertical materno-fetal', true),
('Vinorelbina', 'Alcaloide semisintético de la vinca antineoplásico para cáncer de pulmón no microcítico y mama', true),
('Hidroquinona', 'Agente despigmentante tópico inhibidor de tirosinasa para hiperpigmentación cutánea y melasma', true),
('Aripiprazol', 'Antipsicótico atípico agonista parcial de dopamina D2 y serotonina 5-HT1A para esquizofrenia', true),
('Piridostigmina', 'Inhibidor de acetilcolinesterasa para tratamiento de miastenia gravis', true),
('Sulfato de Magnesio', 'Electrolito para tratamiento de eclampsia preeclampsia hipomagnesemia y como tocolítico', true),
('Corticotrofina (ACTH)', 'Hormona adrenocorticotropa que estimula la síntesis y liberación de cortisol suprarrenal', true),
('Daclatasvir', 'Antiviral de acción directa inhibidor NS5A pan-genotípico del virus de la hepatitis C', true),
('Quetiapina', 'Antipsicótico atípico para esquizofrenia episodios maníacos y depresión bipolar', true),
('Hidróxido de aluminio y magnesio', 'Antiácido combinado de acción local para pirosis y dispepsia', true),
('Sildenafilo', 'Inhibidor selectivo de PDE-5 para disfunción eréctil e hipertensión arterial pulmonar', true),
('Tramadol', 'Analgésico opioide atípico con mecanismo dual inhibición de recaptación de monoaminas para dolor moderado', true),
('Naloxona', 'Antagonista competitivo de receptores opioides antídoto para sobredosis y depresión respiratoria', true),
('Basiliximab', 'Anticuerpo monoclonal quimérico anti-CD25 inmunosupresor de inducción en trasplante renal', true),
('Vitamina D', 'Vitamina liposoluble esencial para absorción de calcio función inmune y homeostasis ósea', true),
('Haloperidol decanoato', 'Éster de depósito del haloperidol de administración intramuscular mensual para adherencia en psicosis', true),
('Lidocaína clorhidrato sin conservante', 'Anestésico local libre de conservantes para uso intratecal epidural o intraarticular', true),
('Atropina sulfato', 'Sal sulfato de atropina anticolinérgico para bradicardia e intoxicación por organofosforados', true),
('Rifampicina, Dapsona', 'Combinación antibacteriana de dos fármacos para lepra paucibacilar según protocolo OMS', true),
('Tiamina (Vitamina B1)', 'Vitamina B1 esencial para metabolismo de carbohidratos y función del sistema nervioso', true),
('Telmisartan', 'ARA II de larga vida media (24h) con efecto metabólico favorable antihipertensivo', true),
('Solución para diálisis intraperitoneal', 'Solución estéril de composición variable para diálisis peritoneal continua', true),
('Ácido Ascórbico (Vitamina C)', 'Ácido ascórbico vitamina antioxidante esencial para síntesis de colágeno e inmunidad celular', true),
('Glicerol (Glicerina bidestilada)', 'Glicerina de alta pureza bidestilada para formulaciones farmacéuticas parenterales y oftálmicas', true),
('Gentamicina', 'Aminoglucósido antibacteriano de amplio espectro para infecciones graves por gram negativos incluyendo Pseudomonas', true),
('Melfalán', 'Agente alquilante mostaza nitrogenada antineoplásico para mieloma múltiple y carcinoma de ovario', true),
('Halotano', 'Anestésico inhalado halogenado de uso histórico actualmente desplazado por agentes más modernos', true),
('Piperacilina', 'Ureidopenicilina de amplio espectro activa frente a Pseudomonas aeruginosa y gram negativos', true),
('Sulfadoxina', 'Sulfonamida de acción prolongada usada en combinación con pirimetamina para malaria', true),
('Cicloserina', 'Antibacteriano de segunda línea análogo de D-alanina para tuberculosis multirresistente y extensamente resistente', true),
('Nistatina', 'Antifúngico poliénico tópico y oral para candidiasis mucocutánea oral vaginal e intestinal', true),
('Fluorouracilo', 'Antimetabolito pirimidínico 5-FU antineoplásico para cáncer colorrectal mama y piel', true),
('Aciclovir', 'Antiviral análogo de guanosina para herpes simple varicela y zóster con acción específica viral', true),
('Codeína', 'Opioide débil analgésico y antitusivo prodrug de la morfina', true),
('Vitamina C', 'Ácido ascórbico vitamina antioxidante esencial para función inmune y síntesis de colágeno', true),
('Inmunoglobulina humana normal', 'Concentrado de inmunoglobulinas IgG para inmunodeficiencias humorales e infecciones graves', true),
('Amilorida', 'Diurético ahorrador de potasio que bloquea canales de sodio epitelial en túbulo colector', true),
('Suero Antilatrodectus', 'Inmunoglobulina equina específica contra el veneno de araña Latrodectus (viuda negra)', true),
('Tiabendazol', 'Bencimidazol antihelmintico para estrongiloidosis larva migrans cutánea y visceral', true),
('Lamotrigina', 'Antiepiléptico de amplio espectro y estabilizador del ánimo en trastorno bipolar', true),
('Salbutamol', 'Broncodilatador beta-2 agonista de acción corta para crisis asmáticas y broncoespasmo', true),
('Etilefrina', 'Simpaticomimético alfa y beta de acción mixta para hipotensión ortostática', true),
('Doxiciclina', 'Tetraciclina semisintética de amplio espectro para infecciones por gérmenes atípicos ETS y malaria', true),
('Ceftazidima', 'Cefalosporina de 3ª generación de elección para infecciones por Pseudomonas aeruginosa', true),
('Leuprolide', 'Análogo de GnRH agonista para cáncer de próstata endometriosis y pubertad precoz', true),
('Pazopanib', 'Inhibidor multikinasa antiangiogénico para carcinoma renal avanzado y sarcoma de partes blandas', true),
('Ácido Fólico', 'Vitamina B9 para prevención de defectos del tubo neural y tratamiento de megaloblastosis', true),
('Solución para dialisis peritoneal II', 'Segunda formulación de solución estéril para diálisis peritoneal continua ambulatoria', true),
('Epinefrina (Adrenalina)', 'Adrenalina catecolamina de emergencia para anafilaxia parada cardíaca y broncoespasmo severo', true),
('Progesterona', 'Hormona progestágena natural para apoyo de fase lútea reproducción asistida y amenaza de aborto', true),
('Beclometasona dipropionato', 'Éster dipropionato de beclometasona corticosteroide inhalado para control del asma', true),
('Ritonavir', 'Inhibidor de proteasa del VIH usado principalmente como potenciador farmacocinético en dosis bajas', true),
('Niclosamida', 'Antihelmintico para tenias intestinales (Taenia saginata, T. solium e Hymenolepis)', true),
('Permetrina', 'Piretroide sintético insecticida antiparasitario tópico para escabiosis y pediculosis', true),
('Aminofilina', 'Xantina broncodilatadora sal de teofilina con etilendiamina para administración parenteral', true),
('Mefloquina (clorhidrato)', 'Sal clorhidrato de mefloquina antipalúdico para profilaxis y tratamiento en zonas de resistencia', true),
('Tetraciclina', 'Antibiótico bacteriostático de amplio espectro para acné H. pylori y enfermedades transmitidas por vectores', true),
('Fentanilo con conservante', 'Opiáceo sintético en formulación estándar con conservantes para uso sistémico analgésico', true),
('Imatinib', 'Inhibidor de BCR-ABL tirosinquinasa revolucionario para leucemia mieloide crónica y GIST', true),
('Clindamicina', 'Lincosamida antibacteriana activa frente a gram positivos y anaerobios para infecciones graves', true),
('Gadopentato de dimeglumina', 'Sal de meglumina del gadopentato medio de contraste iónico para resonancia magnética', true),
('Clotrimazol', 'Antifúngico imidazólico tópico ampliamente usado para candidiasis vaginal y dermatofitosis', true),
('Primaquina (base)', 'Forma base de primaquina antipalúdico para erradicación de hipnozoítos de P. vivax', true),
('Citarabina', 'Análogo nucleosídico de citidina antineoplásico para leucemia aguda y linfoma', true),
('Cisplatino', 'Compuesto de platino antineoplásico de primera generación para tumores sólidos gonadales y ORL', true),
('Cianocobalamina (Vitamina B12)', 'Forma cianocobalamina estable de vitamina B12 para inyección en deficiencias', true),
('Inmunoglobulina anti D (RH)', 'Gammaglobulina anti-D (Rho) para prevención de sensibilización Rh en madres Rh negativas', true),
('Fibrinógeno humano', 'Concentrado del factor de coagulación I para hipofibrinogenemia congénita o adquirida', true),
('Fluticasona', 'Corticosteroide inhalado de alta potencia para asma rinitis alérgica y EPOC', true),
('Oxaliplatino', 'Compuesto de platino de 3ª generación antineoplásico para cáncer colorrectal en combinación con 5-FU', true),
('Retinol (Vitamina A)', 'Forma activa liposoluble de vitamina A esencial para visión crecimiento e inmunidad', true),
('Dextrometorfano bromhidrato', 'Antitusivo no opioide de acción central agonista del receptor sigma para tos seca', true),
('Claritromicina', 'Macrólido semisintético para infecciones por H. pylori micobacterias atípicas y vías respiratorias', true),
('Milrinona', 'Inhibidor selectivo de PDE-3 inotrópico y vasodilatador para insuficiencia cardíaca aguda descompensada', true),
('Complejo de vitaminas y minerales pediátrico (CMV)', 'Suplemento multivitamínico y mineral formulado específicamente para necesidades pediátricas', true),
('Clomipramina', 'Antidepresivo tricíclico de elección para trastorno obsesivo-compulsivo y depresión severa', true),
('Dexmedetomidina', 'Agonista selectivo alfa-2 adrenérgico sedante y analgésico para sedación en UCI y procedimientos', true),
('Insulina Glulisina', 'Análogo de insulina de acción ultrarrápida de inicio más rápido que insulina regular', true),
('Neostigmina', 'Inhibidor reversible de acetilcolinesterasa para reversión del bloqueo neuromuscular y miastenia gravis', true),
('Insulina Glargina', 'Análogo de insulina basal de acción prolongada sin pico para control glucémico nocturno', true),
('Mercaptopurina', 'Antimetabolito tiopurídico antineoplásico e inmunosupresor para leucemia linfoblástica aguda', true),
('Propiltiouracilo', 'Antitirotídeo que inhibe la síntesis de hormonas tiroideas y la conversión de T4 a T3 periférica', true),
('Levodopa', 'Precursor de dopamina que cruza la barrera hematoencefálica principal fármaco para Parkinson', true),
('Oxitocina', 'Hormona uterotónica natural para inducción y conducción del parto y control de hemorragia postparto', true),
('Gonadotrofina coriónica', 'Hormona con actividad LH para inducción de ovulación hipogonadismo masculino y criptorquidia', true),
('Cefradina', 'Cefalosporina de 1ª generación oral para infecciones leves de piel y vías urinarias', true),
('Violeta de genciana (Cloruro de metilrosanilina)', 'Colorante antiséptico tópico para infecciones fúngicas y bacterianas superficiales', true),
('Salmeterol', 'Beta-2 agonista inhalado de acción prolongada para mantenimiento del asma y EPOC siempre con corticosteroide', true),
('Mitomicina', 'Agente alquilante antineoplásico antibiótico para cáncer de vejiga estómago y colon', true),
('Betametasona (valerato)', 'Éster valerato de betametasona corticosteroide tópico de alta potencia para dermatosis', true),
('Estreptoquinasa', 'Fibrinolítico de origen estreptocócico para trombosis venosa profunda embolia pulmonar e IAM', true),
('Hierro elemental (Fe)', 'Hierro elemental micronutriente esencial para síntesis de hemoglobina y transporte de oxígeno', true),
('Clorpromazina', 'Antipsicótico típico fenotiazínico de primera generación para psicosis aguda e hipo intratable', true),
('N-acetilcisteina', 'Mucolítico y hepatoprotector antídoto de intoxicación por paracetamol y precursor del glutatión', true),
('Noradrenalina', 'Catecolamina vasopresora de primera línea en shock séptico que aumenta la resistencia vascular', true),
('Flumazenil', 'Antagonista competitivo de receptores de benzodiacepinas para reversión de sedación y sobredosis', true),
('Ácido Tranexámico', 'Antifibrinolítico inhibidor competitivo de plasminógeno para control de hemorragia quirúrgica y trauma', true),
('Quinina (bisulfato o sulfato)', 'Antipalúdico clásico en sales de bisulfato o sulfato para malaria no complicada', true),
('Abacavir sulfato', 'INTI antirretroviral para VIH en sal sulfato requiere test de HLA-B*5701 previo', true),
('Fluoresceina (sal sódica)', 'Colorante fluorescente de sal sódica para angiografía retiniana y diagnóstico de úlceras corneales', true),
('Ciproterona (acetato)', 'Progestágeno antiandrogénico para hirsutismo acné intenso y cáncer de próstata', true),
('Carboplatino', 'Derivado del platino de 2ª generación antineoplásico con menor nefrotoxicidad que cisplatino', true),
('Remifentanilo', 'Opioide sintético de acción ultrabreve (minutos) para analgesia durante procedimientos quirúrgicos', true),
('Montelukast', 'Antagonista de receptores de cisteinil-leucotrienos para asma bronquial y rinitis alérgica', true),
('Ácido Gadotérico', 'Quelato macrocíclico de gadolinio de alta estabilidad agente de contraste para resonancia magnética', true),
('Metildopa (Alfametildopa)', 'Antihipertensivo de acción central de primera elección para hipertensión en el embarazo', true),
('Imipramina clorhidrato', 'Antidepresivo tricíclico para depresión mayor y enuresis nocturna en niños', true),
('Solución para dialisis peritoneal I', 'Primera formulación de solución estéril de dextrosa para diálisis peritoneal', true),
('Mesalazina', 'Antiinflamatorio aminosalicilato tópico intestinal para colitis ulcerosa y enfermedad de Crohn', true),
('Colistina', 'Polimixina E antibiótica de último recurso parenteral e inhalada para gram negativos multirresistentes (XDR)', true),
('Carbamazepina', 'Antiepiléptico estabilizador de membrana y de primera línea para neuralgia del trigémino y bipolar', true),
('Tiopental sódico', 'Barbitúrico de acción ultrabreve inductor anestésico intravenoso histórico', true),
('Morfina', 'Opioide agonista mu de referencia analgésico patrón para dolor severo oncológico y postoperatorio', true),
('Talidomida', 'Inmunomodulador con actividad antiangiogénica para mieloma múltiple y eritema nudoso leproso (uso restringido)', true),
('Butilbromuro de Hioscina (Butilescopolamina)', 'Antiespasmódico anticolinérgico periférico para cólico abdominal biliar y ureteral', true),
('Clopidogrel', 'Antiagregante plaquetario tienopiridínico para síndrome coronario agudo y prevención de eventos aterotrombóticos', true),
('Prazicuantel', 'Antihelmintico para esquistosomiasis y tenias (ortografía alternativa de praziquantel)', true),
('Asparaginasa', 'Enzima antineoplásica que depleta L-asparagina sérica para leucemia linfoblástica aguda', true),
('Lamivudine', 'Nombre en inglés de lamivudina INTI antirretroviral para VIH y hepatitis B', true),
('Ciclosporina', 'Inmunosupresor calcineurínico inhibidor de IL-2 para prevención de rechazo en trasplantes y autoinmunes', true),
('Dapsona', 'Sulfona antibacteriana antiinflamatoria para lepra neumocistosis y dermatitis herpetiforme', true),
('Solución de Manitol', 'Diurético osmótico intravenoso al 15-20% para edema cerebral e hipertensión intracraneal', true),
('Gadodiamida', 'Quelato lineal no iónico de gadolinio para contraste en resonancia magnética', true),
('Ácido Valpróico / Valproato sódico', 'Anticonvulsivante de amplio espectro y estabilizador del ánimo para epilepsia y bipolar', true),
('Morfina (con y sin conservante)', 'Opioide de referencia en formulaciones con o sin conservantes para vías sistémica espinal y epidural', true),
('Pirantel pamoato', 'Antihelmintico para nematodos intestinales especialmente áscaris y oxiuros en dosis única', true),
('Bupivacaina clorhidrato (pesada)', 'Solución hiperbara de bupivacaína con glucosa para anestesia espinal subaracnoidea', true),
('Rifampicina', 'Antibiótico rifamicínico bactericida de primera línea para tuberculosis y lepra', true),
('Cloruro de potasio', 'Electrolito para corrección de hipopotasemia e hipocaliemia en fluidoterapia', true),
('Vacuna Antirrábica', 'Vacuna inactivada para profilaxis pre y postexposición contra el virus de la rabia', true),
('Cetirizina', 'Antihistamínico de 2ª generación con escasa sedación para alergias urticaria y rinitis', true),
('Benznidazol', 'Antiprotozoario nitroimidazólico de primera línea para enfermedad de Chagas en fase aguda', true),
('Hidrocortisona succinato sódico', 'Forma soluble de hidrocortisona para administración intravenosa en urgencias endocrinológicas', true),
('Filgrastim', 'Factor estimulante de colonias granulocíticas G-CSF para neutropenia post-quimioterapia', true),
('Lumefantrina', 'Antimalárico aminoalcohol usado exclusivamente en combinación con artemeter para malaria no complicada', true),
('Trolamina', 'Base orgánica trietanolamina usada como neutralizante y emulsificante en formulaciones tópicas', true),
('Resorcinol', 'Queratolítico antiséptico tópico para acné y dermatitis seborreica', true),
('Tenofovir disoproxilo', 'Profármaco del tenofovir INTI para VIH y hepatitis B crónica', true),
('Doxorubicina clorhidrato (Adriamicina)', 'Antraciclina en forma de sal clorhidrato (Adriamicina) antineoplásica', true),
('Colecalciferol (Vitamina D3)', 'Vitamina D3 natural para metabolismo óseo absorción intestinal de calcio y función inmune', true),
('Alopurinol', 'Inhibidor de xantina oxidasa que reduce la producción de ácido úrico para gota crónica', true),
('Voriconazol', 'Antifúngico triazólico de amplio espectro de primera línea para aspergilosis invasiva y candidiasis', true),
('Peróxido de Benzoílo', 'Agente antimicrobiano y queratolítico tópico de primera línea para acné vulgar', true),
('Hidroclorotiazida', 'Diurético tiazídico para hipertensión arterial edema leve e insuficiencia cardíaca leve', true),
('Nafazolina clorhidrato', 'Imidazolina simpaticomimética descongestionante nasal y ocular de acción local', true),
('Gemfibrozilo', 'Fibrato ácido fíbrico hipolipemiante que reduce triglicéridos y aumenta HDL', true),
('Vacuna cuadrivalente VPH', 'Vacuna preventiva contra los serotipos 6, 11, 16 y 18 del virus del papiloma humano', true),
('Minociclina', 'Tetraciclina semisintética de amplio espectro para acné infecciones por gérmenes atípicos y MRSA', true),
('Deferoxamina mesilato', 'Quelante parenteral de hierro para intoxicación aguda por hierro y hemocromatosis', true),
('Protamina Sulfato', 'Proteína catiónica antídoto específico de la heparina que revierte su efecto anticoagulante', true),
('Petidina (Meperidina)', 'Opioide sintético de acción rápida y duración corta para dolor moderado a severo', true),
('Lágrimas artificiales', 'Solución lubricante oftálmica que simula la película lagrimal para síndrome de ojo seco', true),
('Clomipramina (clorhidrato)', 'Sal clorhidrato del antidepresivo tricíclico clomipramina para TOC y depresión severa', true),
('Nitrofurantoína', 'Antibacteriano nitrofuránico oral de primera línea para infecciones urinarias no complicadas', true),
('Cloxacilina', 'Isoxazolil-penicilina resistente a penicilinasas para Staphylococcus aureus sensible a meticilina', true),
('Bisacodilo', 'Laxante estimulante de contacto que actúa sobre la mucosa del colon para estreñimiento', true),
('Antihistamínico (genérico)', 'Fármaco antagonista de receptores H1 de histamina para reacciones alérgicas', true),
('Abacavir', 'INTI antirretroviral análogo de guanosina para combinaciones en VIH (requiere test HLA-B*5701)', true),
('Bleomicina', 'Antibiótico glicopeptídico antitumoral para linfoma de Hodgkin carcinomas y derrame pleural maligno', true),
('Metoclopramida', 'Procinético y antiemético antagonista dopaminérgico para náuseas vómitos y gastroparesia', true),
('Amfotericina B', 'Antifúngico poliénico de amplio espectro para micosis sistémicas graves (ortografía alternativa)', true),
('Vacuna pentavalente (DPT, HB, Hib)', 'Vacuna combinada contra difteria tétanos tos ferina hepatitis B y Haemophilus influenzae b', true),
('Sales de rehidratación oral (SRO) baja osmolaridad', 'Fórmula mejorada de la OMS con menor osmolaridad para rehidratación en diarrea aguda infantil', true),
('Zinc (como sulfato)', 'Zinc en forma de sulfato micronutriente para tratamiento de diarrea infantil y deficiencias', true),
('Benzoato de bencilo', 'Antiparasitario tópico de primera línea para escabiosis y pediculosis', true),
('Piridoxina clorhidrato (Vitamina B6)', 'Forma clorhidrato de vitamina B6 para neuropatía periférica por isoniazida y deficiencias vitamínicas', true),
('Antiinfeccioso de acción tópica', 'Agente antimicrobiano de espectro variable para aplicación local en piel y mucosas', true),
('Nitroprusiato de sodio', 'Vasodilatador arterial y venoso potente de acción inmediata para crisis hipertensivas graves', true),
('Ifosfamida', 'Agente alquilante oxazafosforina antineoplásico para sarcomas y linfomas siempre con mesna', true),
('Vacuna antihepatitis B', 'Vacuna recombinante del antígeno HBsAg para inmunización activa contra el virus de la hepatitis B', true),
('Lidocaína clorhidrato', 'Sal clorhidrato del anestésico local lidocaína para infiltración y bloqueos nerviosos', true),
('Bencilpenicilina sódica', 'Penicilina G cristalina sódica de alta solubilidad para administración intravenosa en infecciones graves', true),
('Vacuna antipoliomielítica bivalente', 'Vacuna oral de virus vivos atenuados bivalente (Sabin) contra poliovirus tipo 1 y 3', true),
('Suero Antirrábico (heterólogo)', 'Inmunoglobulina antirrábica equina heteróloga para profilaxis postexposición pasiva inmediata', true),
('Delamanid', 'Nitroimidazo-oxazol antibacteriano de nueva clase para tuberculosis multirresistente e intolerante a otros fármacos', true),
('Pirimetamina', 'Antipalúdico inhibidor de dihidrofolato reductasa parasitaria para malaria y toxoplasmosis', true),
('Atorvastatina', 'Estatina de alta potencia inhibidora de HMG-CoA reductasa ampliamente usada para dislipemia', true),
('Biperideno clorhidrato', 'Anticolinérgico antiparkinsoniano para control de síntomas extrapiramidales por antipsicóticos', true),
('Vitamina A (Retinol)', 'Vitamina A (retinol) para prevención de ceguera nocturna y déficit en países en desarrollo', true),
('Hidroxiurea', 'Inhibidor de ribonucleótido reductasa antineoplásico e inmunomodulador para leucemia mieloide crónica y drepanocitosis', true),
('Capreomicina', 'Antibiótico péptido cíclico inyectable de segunda línea para tuberculosis multirresistente', true),
('Vaselina liquida', 'Aceite mineral de parafina lubricante emoliente y laxante oral', true),
('Aminoácidos', 'Mezcla de aminoácidos esenciales y no esenciales para nutrición parenteral total', true),
('Fluoresceina', 'Colorante fluorescente xanteno para angiografía retiniana y detección de lesiones corneales', true),
('Proteinas para alimentación enteral', 'Suplemento proteico para soporte nutricional enteral en pacientes con necesidades aumentadas', true),
('Óxido de Zinc con o sin aceite', 'Protector dérmico y cicatrizante para eritema del pañal y lesiones cutáneas', true),
('Clomifeno citrato', 'Modulador selectivo de receptores de estrógeno (SERM) inductor de ovulación para infertilidad anovulatoria', true),
('Vacuna Antirrábica de uso Humano (Cultivo Celular)', 'Vacuna antirrábica inactivada producida en células Vero para profilaxis pre y postexposición', true),
('Dopamina clorhidrato', 'Catecolamina con efectos dopaminérgicos inotrópicos y vasopresores dependientes de la dosis infundida', true),
('Ácido Zoledrónico', 'Bifosfonato de 3ª generación de alta potencia para osteoporosis metástasis óseas e hipercalcemia maligna', true),
('Nitazoxanida', 'Antiprotozoario y antihelmintico tiazolida de amplio espectro para giardiasis criptosporidiosis y helmintos', true),
('Meropenem', 'Carbapenémico de amplio espectro con mejor perfil de tolerabilidad neurológica que imipenem', true),
('Bicarbonato de sodio', 'Tampón alcalino para corrección de acidosis metabólica y alcalinización urinaria', true),
('Nevirapina', 'INNTI antirretroviral de primera generación para VIH especialmente en profilaxis de transmisión vertical', true),
('Domperidona', 'Procinético y antiemético antagonista periférico D2 con escaso efecto central', true),
('Ciprofloxacina', 'Fluoroquinolona de 2ª generación de amplio espectro (forma alternativa de ciprofloxacino)', true),
('Moxifloxacina', 'Fluoroquinolona de 4ª generación con actividad anaeróbica atípica y antituberculosa', true),
('Globulina Anti-timocito', 'Inmunoglobulina para aplasia medular grave y profilaxis de rechazo agudo en trasplante', true),
('Pentamidina', 'Antiprotozoario diamidínico para neumocistosis por P. jirovecii y leishmaniasis visceral', true),
('Factor IX de la coagulación', 'Concentrado de factor IX para tratamiento de hemofilia B (enfermedad de Christmas)', true),
('Ácido aminocapróico', 'Antifibrinolítico inhibidor de la activación del plasminógeno para hemorragia quirúrgica grave', true),
('Ácido Alendrónico (Alendronato)', 'Bifosfonato de primera línea para osteoporosis posmenopáusica y enfermedad de Paget ósea', true),
('Vacuna contra Influenza (Pediátrica)', 'Vacuna antigripal trivalente o tetravalente formulada y dosificada para niños', true),
('Tioridazina', 'Antipsicótico típico fenotiazínico actualmente restringido por riesgo de arritmias cardíacas (QTc)', true),
('Tiamazol (Metimazol)', 'Antitirotídeo que inhibe la síntesis de hormonas tiroideas para hipertiroidismo y tiroides de Graves', true),
('Temozolomida', 'Agente alquilante antineoplásico oral para glioblastoma multiforme y astrocitoma anaplásico', true),
('Gadoversetamida', 'Quelato lineal no iónico de gadolinio para contraste en resonancia magnética del SNC', true),
('Agentes con gelatina', 'Hemostáticos locales absorbibles o expansores plasmáticos (gelatinas modificadas) para reposición de volumen', true),
('Bevacizumab', 'Anticuerpo monoclonal anti-VEGF antiangiogénico para cáncer colorrectal pulmón y ovario metastásico', true),
('Indometacina', 'AINE potente inhibidor de COX para artritis gotosa aguda y cierre del ductus arterioso en neonatos', true),
('Ergotamina tartrato', 'Alcaloide del ergot agonista alfa-adrenérgico y serotoninérgico para tratamiento agudo de migraña', true),
('Vacuna contra Influenza (Adulto)', 'Vacuna antigripal trivalente o tetravalente inactivada para adultos actualizada anualmente', true),
('Aceite mineral', 'Laxante lubricante que reblandece las heces y parafina líquida emoliente tópica', true),
('Isoniazida', 'Antibacteriano bactericida de primera línea para tuberculosis activa y quimioprofilaxis', true),
('Vacuna Triple DPT (Difteria, Pertusis, Tetanos)', 'Vacuna combinada de toxoides y antígenos contra difteria tos ferina y tétanos', true);
